version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: DostavimVseDockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=admin --execute \"SHOW
        DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 20
    ports:
      - "3306:3306"
